services:
  # Infrastructure services
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./config-server/secrets:/app/secrets
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - trotot-network

  discovery:
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - trotot-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8222:8222"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      - discovery
    networks:
      - trotot-network

  # Core services
  address-service:
    build:
      context: ./address-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      - discovery
      - config-server
    networks:
      - trotot-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - JSON_FILE_PATH=/app/config/notification-config.json
    volumes:
      - ./notification-service/config:/app/config
    depends_on:
      - discovery
      - config-server
    networks:
      - trotot-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      - discovery
      - config-server
    networks:
      - trotot-network

  room-service:
    build:
      context: ./room-service
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
    depends_on:
      - discovery
      - config-server
      # - notification-service
    networks:
      - trotot-network

  # auth-service:
  #   build:
  #     context: ./auth-service
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
  #     - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
  #   depends_on:
  #     - discovery
  #     - config-server
  #     - notification-service
  #     - user-service
  #   networks:
  #     - trotot-network

  # media-service:
  #   build:
  #     context: ./media-service
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
  #     - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
  #   depends_on:
  #     - discovery
  #     - config-server
  #   networks:
  #     - trotot-network

  # payment-service:
  #   build:
  #     context: ./payment-service
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
  #     - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
  #   depends_on:
  #     - discovery
  #     - config-server
  #   networks:
  #     - trotot-network

  # review-service:
  #   build:
  #     context: ./review-service
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
  #     - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
  #   depends_on:
  #     - discovery
  #     - config-server
  #   networks:
  #     - trotot-network

  # report-service:
  #   build:
  #     context: ./report-service
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
  #     - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
  #   depends_on:
  #     - discovery
  #     - config-server
  #   networks:
  #     - trotot-network
      
  # recommendation-service:
  #   build:
  #     context: ./recommendation-service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - EUREKA_SERVER=http://discovery:8761/eureka/
  #   volumes:
  #     - ./recommendation-service/models:/app/models
  #   depends_on:
  #     - discovery
  #     - config-server
  #     - room-service
  #     - user-service
  #   networks:
  #     - trotot-network

networks:
  trotot-network:
    driver: bridge