eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/api/v1/rooms/**
          filters:
            - AuthenticationFilter
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/api/v1/addresses/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: [ "GET", "POST", "PUT", "DELETE" ]
            allowedHeaders: [ "*" ]
            allowCredentials: true
application:
  config:
    users-url: http://localhost:8222/api/v1/users