eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: room-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/rooms/**
        - id: address-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/addresses/**
        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**