eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8050
spring:
  application:
    name: auth-service

application:
  config:
    users-url: http://localhost:8222/api/v1/users
