eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8050
spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/trotot_auth?createDatabaseIfNotExist=true
    username: root
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: redis
    port: 6379
    timeout: 60000

application:
  config:
    users-url: http://localhost:8222/api/v1/users
