eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8010
spring:
  application:
    name: report-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/report_db
    username: root
    password: sapassword
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ngovantoan0986@gmail.com
    password: sufy dfpt sgmg rnjw
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
