eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070
spring:
  application:
    name: room-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/trotot_room?createDatabaseIfNotExist=true
    username: root
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update

application:
  config:
    addresses-url: http://localhost:8222/api/v1/addresses