eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8090
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3307/trotot_user?createDatabaseIfNotExist=true"
    username: root
    password: sapassword
  jpa:
    hibernate:
      ddl-auto: update
