spring:
  application:
    name: address-service
  config:
    import: optional:configserver:http://config-server:8888

  cache:
    type: redis

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000
      keepalive-time: 300000