spring:
  application:
    name: review-service
    config:
        import: optional:configserver:http://localhost:8888
#  datasource:
#    url: jdbc:mariadb://localhost:3306/reviewdb
#    username: root
#    password: sapassword
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#server:
#  port: 8080
